on:
  push:
    branches: [ "*" ]
    tags: ["*"]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - name: Install system dependecies
      run: |
        apt update
        apt install --no-install-recommends --no-upgrade -y git nodejs curl ca-certificates        

    # - name: Install dependecies
    #   run: |
    #     apt install --no-install-recommends --no-upgrade -y just zip gnupg libassuan-dev libgpgme-dev        

    - name: Install Pkl
      uses: https://github.com/pkl-community/setup-pkl@v0.0.5
      with:
        pkl-version: "0.26.3"

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run tests
      run: |
        pkl test

    - name: Package project
      run: |
        pkl project package

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts.zip
        path: .out/**

    - name: Release
      uses: https://github.com/softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: .out/**