on:
    push:
      branches: [ "*" ]
      tags: ["*"]
    pull_request:
      branches: [ "*" ]
  
jobs:
  test:
    runs-on: ubuntu-24.04

    permissions:
        # todo: isolate release workflow, only it needs this permission
        contents: write

    steps:
    - name: Install Pkl
      uses: pkl-community/setup-pkl@v0.0.5
      with:
        pkl-version: "0.26.3"

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run tests
      run: |
        pkl test

    - name: Package project
      run: |
        mkdir -p out
        pkl project package --output-path out

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts.zip
        path: out/*

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: out/*