on: [push]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - name: Install Pkl
      uses: pkl-community/setup-pkl@v0.0.5
      with:
        pkl-version: "0.26.3"

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run tests
      run: |
        pkl test
